
AS=as --32

all: start load header.bin

start:start.S
	gcc -m32 -c start.S
	ld -m elf_i386 -Ttext 0x7c00 -o start.elf start.o
	objcopy -O binary   start.elf start
load: loader.S loadmain.c
	gcc -m32 -c loader.S
	gcc -m32 -fno-builtin  -fno-stack-protector  -O -c loadmain.c
	ld -m elf_i386 -Ttext 0x7d00 -o loader.elf loader.o loadmain.o
	objcopy -O binary loader.elf load

copy.o:copy.S
	gcc -m16  -fno-builtin -mregparm=3 -c copy.S

bioscall.o:bioscall.S
	gcc -m16 -c -mregparm=3  bioscall.S
main.o: main.c
	gcc -m16 -mregparm=3 -fno-builtin -fno-stack-protector -c main.c
tty.o: tty.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c tty.c
regs.o: regs.c header_32.h
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector -c regs.c


memory.o: memory.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c memory.c
video.o: video.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c video.c
video-vesa.o: video-vesa.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c video-vesa.c
video-vga.o: video-vga.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c video-vga.c
video-bios.o: video-bios.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c video-bios.c


printf.o: printf.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c printf.c
string.o: string.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c string.c


pm.o: pm.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c pm.c

a20.o:a20.c
	gcc -m16 -fno-builtin -mregparm=3 -fno-stack-protector  -c a20.c
pmjump.o:pmjump.S
	gcc  -m32  -fno-builtin -mregparm=3 -c pmjump.S



header.bin: header.S main.o copy.o tty.o regs.o bioscall.o memory.o video.o video-vesa.o video-vga.o video-bios.o pm.o a20.o pmjump.o  printf.o string.o
	gcc -m32 -c header.S
	ld   -m elf_i386 -T head.ld -o header.elf header.o main.o  memory.o video.o video-vesa.o video-vga.o video-bios.o  pm.o a20.o pmjump.o printf.o string.o tty.o regs.o copy.o bioscall.o
	objcopy -O binary header.elf header.bin


install:
	dd if=start of=c.img bs=512 conv=notrunc
	dd if=load of=c.img bs=512 seek=1 conv=notrunc
	dd if=header.bin of=c.img bs=512 seek=6 conv=notrunc
	dd if=kernel/arch/head_64.bin of=c.img bs=512 seek=70 conv=notrunc
	dd if=kernel/arch/kernel/head_64.elf of=c.img bs=512 seek=80 conv=notrunc
clean:
	rm  *.o start load *.bin *.elf
